# Generated by Django 5.1.4 on 2024-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaicertificate_delete_chaiingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
    ]
